services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sentinel_ids
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend
    command: ["./wait_for_db.sh"]
    volumes:
      - ./backend:/app
      - ./ml_engine:/app/ml_engine
      - ./datasets:/app/datasets
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
