# Generated by Django 4.2.7 on 2026-03-29 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('slack_integration', models.BooleanField(default=False)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('auto_block_threats', models.BooleanField(default=False)),
                ('ip_whitelisting', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30)),
                ('retention_days', models.IntegerField(default=90)),
                ('auto_archive', models.BooleanField(default=True)),
                ('ai_model_mode', models.CharField(choices=[('standard', 'Standard'), ('advanced', 'Advanced'), ('deep', 'Deep Learning')], default='advanced', max_length=20)),
                ('continuous_learning', models.BooleanField(default=True)),
                ('ai_sensitivity', models.IntegerField(default=85)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
