# Generated by Django 4.2.7 on 2026-03-29 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemSettings',
            new_name='SystemSetting',
        ),
    ]
