import { useState } from "react";
import { Link } from "react-router";
import {
  Shield,
  Activity,
  Brain,
  Globe,
  AlertTriangle,
  ArrowRight,
  Lock,
  Zap,
  BarChart2,
  ChevronDown,
  Plus,
  Minus,
} from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Detection",
    desc: "Gemini-powered semantic analysis classifies threats with 96%+ confidence in real time.",
  },
  {
    icon: Activity,
    title: "Live Threat Monitoring",
    desc: "WebSocket-driven dashboard shows every ingested log and alert the moment it arrives.",
  },
  {
    icon: Globe,
    title: "Network Visualisation",
    desc: "Geographical attack maps and heatmaps show where threats originate across the globe.",
  },
  {
    icon: BarChart2,
    title: "ML Anomaly Detection",
    desc: "Random Forest model trained on UNSW-NB15 catches statistical anomalies rules miss.",
  },
  {
    icon: AlertTriangle,
    title: "Attack Chain Correlation",
    desc: "Batch logs are analysed as sequences — full APT kill chains are detected automatically.",
  },
  {
    icon: Lock,
    title: "Role-Based Access",
    desc: "Admin, Analyst, and Viewer roles keep sensitive data in the right hands.",
  },
];

const stats = [
  { value: "98.2%", label: "Detection Accuracy" },
  { value: "<50ms", label: "Alert Latency" },
  { value: "12", label: "Attack Chain Patterns" },
  { value: "3-Layer", label: "Detection Pipeline" },
];

const faqs = [
  {
    question: "How does Sentinel-IDS combine ML and AI?",
    answer:
      "Sentinel-IDS uses a multi-layered approach. First, a Random Forest model (ML) identifies statistical anomalies in network traffic. Then, if suspicious activity is found, the system uses Gemini AI to perform semantic analysis on the log messages, providing a natural language explanation and high-confidence classification.",
  },
  {
    question: "What types of logs can be ingested?",
    answer:
      "The system is designed to ingest standard network logs (JSON/CSV), system auth logs, and web server logs (Nginx/Apache). It normalizes these diverse inputs into a standard format for the detection engine.",
  },
  {
    question: "How are attack chains detected?",
    answer:
      "Our correlation engine looks for sequences of events over time. By analyzing batches of logs rather than isolated entries, it can spot patterns like lateral movement, reconnaissance followed by exploitation, and data exfiltration.",
  },
  {
    question: "Is there a delay in alert delivery?",
    answer:
      "No. Alerts are pushed via WebSockets the instant they are generated by the detection service, ensuring sub-50ms latency between detection and dashboard visualization.",
  },
  {
    question: "How do I get an account?",
    answer:
      "You can request access via the registration page. Once submitted, a system administrator will review your request and activate your account. You will then be able to log in with your chosen credentials.",
  },
];

const FaqItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-[#334155]">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full py-6 flex items-center justify-between text-left hover:text-[#22D3EE] transition-colors"
      >
        <span className="text-lg font-medium">{question}</span>
        {isOpen ? (
          <Minus className="w-5 h-5 text-[#22D3EE]" />
        ) : (
          <Plus className="w-5 h-5 text-gray-500" />
        )}
      </button>
      <div
        className={`overflow-hidden transition-all duration-300 ease-in-out ${
          isOpen ? "max-h-96 pb-6" : "max-h-0"
        }`}
      >
        <p className="text-gray-400 leading-relaxed">{answer}</p>
      </div>
    </div>
  );
};

export default function Home() {
  return (
    <div className="min-h-screen bg-[#0F172A] text-white">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#0F172A]/80 backdrop-blur border-b border-[#334155]">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 bg-gradient-to-br from-[#22D3EE] to-[#0EA5E9] rounded-lg flex items-center justify-center">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-bold">Sentinel-IDS</span>
          </div>
          <div className="flex items-center gap-3">
            <Link
              to="/login"
              className="px-4 py-2 border border-[#22D3EE] rounded-lg text-sm text-gray-300 hover:text-white hover:border-none hover:bg-[#22D3EE] transition-colors active:bg-[#0EA5E9]"
            >
              Sign In
            </Link>
            <Link
              to="/register"
              className="px-4 py-2 text-sm bg-[#22D3EE] text-white rounded-lg active:bg-[#0EA5E9] hover:bg-transparent hover:border hover:border-[#22D3EE] transition-colors"
            >
              Request Access
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-40 pb-20 px-6 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full pointer-events-none">
          <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-[#22D3EE]/10 blur-[100px] rounded-full" />
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#0EA5E9]/10 blur-[120px] rounded-full" />
        </div>

        <div className="max-w-4xl mx-auto text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-[#22D3EE]/10 border border-[#22D3EE]/30 rounded-full text-sm text-[#22D3EE] mb-6">
            <Zap className="w-3.5 h-3.5" />
            AI-Powered Intrusion Detection
          </div>
          <h1 className="text-5xl md:text-7xl font-bold leading-tight mb-6">
            The next generation of{" "}
            <span className="bg-gradient-to-r from-[#22D3EE] to-[#0EA5E9] bg-clip-text text-transparent">
              Network Security
            </span>
          </h1>
          <p className="text-xl text-gray-400 mb-10 max-w-2xl mx-auto">
            Sentinel-IDS combines rule-based detection, machine learning anomaly
            scoring, and AI semantic analysis into a single real-time security
            dashboard.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <Link
              to="/register"
              className="flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-[#22D3EE] to-[#0EA5E9] text-white font-semibold rounded-lg hover:shadow-xl hover:shadow-[#22D3EE]/30 transition-all hover:-translate-y-1"
            >
              Request Access <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              to="/dashboard"
              className="flex items-center gap-2 px-8 py-4 border border-[#334155] text-gray-300 rounded-lg hover:border-[#22D3EE]/50 hover:text-white transition-all bg-[#1E293B]/50"
            >
              View Dashboard
            </Link>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-16 border-y border-[#334155] bg-[#1E293B]/20">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-12">
            {stats.map((s) => (
              <div key={s.label} className="text-center group">
                <p className="text-4xl font-bold text-[#22D3EE] mb-2 group-hover:scale-110 transition-transform">
                  {s.value}
                </p>
                <p className="text-sm font-medium text-gray-400 uppercase tracking-wider">
                  {s.label}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-6 bg-gradient-to-b from-transparent to-[#1E293B]/10">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">
              Comprehensive Security Architecture
            </h2>
            <p className="text-gray-400 max-w-xl mx-auto text-lg">
              A complete IDS pipeline from raw log ingestion to AI-classified
              alerts, all in one dashboard.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((f) => {
              const Icon = f.icon;
              return (
                <div
                  key={f.title}
                  className="group bg-[#1E293B] border border-[#334155] rounded-2xl p-8 hover:border-[#22D3EE]/50 transition-all hover:shadow-2xl hover:shadow-[#22D3EE]/5"
                >
                  <div className="w-12 h-12 bg-[#22D3EE]/10 rounded-xl flex items-center justify-center mb-6 group-hover:bg-[#22D3EE]/20 transition-colors">
                    <Icon className="w-6 h-6 text-[#22D3EE]" />
                  </div>
                  <h3 className="text-xl font-bold text-white mb-3">
                    {f.title}
                  </h3>
                  <p className="text-gray-400 leading-relaxed">{f.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* FAQs */}
      <section className="py-24 px-6 border-t border-[#334155]">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-gray-400 text-lg">
              Everything you need to know about the Sentinel-IDS platform.
            </p>
          </div>
          <div className="space-y-2">
            {faqs.map((faq, idx) => (
              <FaqItem key={idx} question={faq.question} answer={faq.answer} />
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 relative">
        <div className="max-w-4xl mx-auto text-center bg-gradient-to-br from-[#1E293B] to-[#0F172A] border border-[#334155] rounded-3xl p-16 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-[#22D3EE]/5 blur-[80px] rounded-full -mr-32 -mt-32" />
          <div className="absolute bottom-0 left-0 w-64 h-64 bg-[#0EA5E9]/5 blur-[80px] rounded-full -ml-32 -mb-32" />

          <div className="w-20 h-20 bg-gradient-to-br from-[#22D3EE] to-[#0EA5E9] rounded-2xl flex items-center justify-center mx-auto mb-8 shadow-lg shadow-[#22D3EE]/20">
            <Shield className="w-10 h-10 text-white" />
          </div>
          <h2 className="text-4xl font-bold mb-6">
            Ready to secure your infrastructure?
          </h2>
          <p className="text-xl text-gray-400 mb-10 max-w-xl mx-auto">
            Join thousands of security professionals using Sentinel-IDS to
            protect their critical network infrastructure.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <Link
              to="/register"
              className="inline-flex items-center gap-2 px-10 py-4 bg-gradient-to-r from-[#22D3EE] to-[#0EA5E9] text-white font-bold rounded-xl hover:shadow-2xl hover:shadow-[#22D3EE]/40 transition-all hover:-translate-y-1"
            >
              Start Free Trial <ArrowRight className="w-5 h-5" />
            </Link>
          </div>
          <p className="mt-6 text-sm text-gray-500">
            No credit card required. Admin approval takes less than 24 hours.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[#334155] pt-16 pb-12 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-12">
            <div className="col-span-1 md:col-span-2">
              <div className="flex items-center gap-2.5 mb-6">
                <div className="w-10 h-10 bg-gradient-to-br from-[#22D3EE] to-[#0EA5E9] rounded-lg flex items-center justify-center">
                  <Shield className="w-6 h-6 text-white" />
                </div>
                <span className="text-xl font-bold">Sentinel-IDS</span>
              </div>
              <p className="text-gray-400 max-w-sm leading-relaxed mb-6">
                Next-generation intrusion detection system leveraging the power
                of AI and machine learning to secure modern digital
                infrastructures.
              </p>
            </div>
            <div>
              <h4 className="font-bold text-white mb-6 uppercase text-xs tracking-widest">
                Product
              </h4>
              <ul className="space-y-4 text-sm text-gray-400">
                <li>
                  <Link to="/features" className="hover:text-[#22D3EE]">
                    Features
                  </Link>
                </li>
                <li>
                  <Link to="/pricing" className="hover:text-[#22D3EE]">
                    Pricing
                  </Link>
                </li>
                <li>
                  <Link to="/api" className="hover:text-[#22D3EE]">
                    API Docs
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold text-white mb-6 uppercase text-xs tracking-widest">
                Company
              </h4>
              <ul className="space-y-4 text-sm text-gray-400">
                <li>
                  <Link to="/about" className="hover:text-[#22D3EE]">
                    About Us
                  </Link>
                </li>
                <li>
                  <Link to="/contact" className="hover:text-[#22D3EE]">
                    Contact
                  </Link>
                </li>
                <li>
                  <Link to="/privacy" className="hover:text-[#22D3EE]">
                    Privacy Policy
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="pt-8 border-t border-[#334155] flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-gray-500">
            <p>© 2026 Sentinel-IDS. All rights reserved.</p>
            <div className="flex items-center gap-6">
              <a href="#" className="hover:text-white transition-colors">
                Twitter
              </a>
              <a href="#" className="hover:text-white transition-colors">
                GitHub
              </a>
              <a href="#" className="hover:text-white transition-colors">
                LinkedIn
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
