import { Download, Search } from "lucide-react";
import { useState } from "react";

export function ReportsHistoryTable({
  history = [],
  loading = false,
  onDownload,
}) {
  const [searchQuery, setSearchQuery] = useState("");

  const filtered = history.filter(
    (r) =>
      r.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      r.report_type?.toLowerCase().includes(searchQuery.toLowerCase()),
  );

  const formatBadgeColor = (fmt) =>
    ({
      pdf: "bg-[#EF4444]/20 text-[#EF4444]",
      csv: "bg-[#10B981]/20 text-[#10B981]",
      json: "bg-[#22D3EE]/20 text-[#22D3EE]",
    })[fmt?.toLowerCase()] ?? "bg-[#F59E0B]/20 text-[#F59E0B]";

  return (
    <div className="bg-[#1E293B] border border-[#334155] rounded-lg p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-lg font-semibold text-white">
            Generated Reports History
          </h3>
          <p className="text-sm text-gray-400 mt-1">
            Download and manage previously generated reports
          </p>
        </div>
      </div>

      <div className="mb-6">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search reports..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#0F172A] border border-[#334155] rounded-lg pl-10 pr-4 py-2.5 text-white placeholder-gray-500 focus:outline-none focus:border-[#22D3EE] transition-colors"
          />
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-[#334155]">
              {[
                "Report Name",
                "Report Type",
                "Date Generated",
                "Generated By",
                "Format",
                "Action",
              ].map((h, i) => (
                <th
                  key={h}
                  className={`text-${i === 5 ? "right" : "left"} text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4`}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[#334155]">
            {loading ? (
              Array(4)
                .fill(0)
                .map((_, i) => (
                  <tr key={i}>
                    <td colSpan={6} className="py-4 px-4">
                      <div className="h-4 bg-gray-700 rounded animate-pulse" />
                    </td>
                  </tr>
                ))
            ) : filtered.length === 0 ? (
              <tr>
                <td
                  colSpan={6}
                  className="py-12 text-center text-gray-400 text-sm"
                >
                  {searchQuery
                    ? "No reports match your search."
                    : "No reports generated yet."}
                </td>
              </tr>
            ) : (
              filtered.map((report) => (
                <tr
                  key={report.id}
                  className="hover:bg-[#0F172A] transition-colors"
                >
                  <td className="py-4 px-4">
                    <p className="text-sm font-medium text-white">
                      {report.name}
                    </p>
                    <p className="text-xs text-gray-400 mt-1">
                      {report.file_size_display ?? "—"}
                    </p>
                  </td>
                  <td className="py-4 px-4 text-sm text-gray-300">
                    {report.report_type
                      ?.replace(/_/g, " ")
                      .replace(/\b\w/g, (c) => c.toUpperCase())}
                  </td>
                  <td className="py-4 px-4 text-sm text-gray-300">
                    {report.generated_at
                      ? new Date(report.generated_at).toLocaleString("en-GB", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        })
                      : "—"}
                  </td>
                  <td className="py-4 px-4 text-sm text-gray-300">
                    {report.generated_by ?? "System"}
                  </td>
                  <td className="py-4 px-4">
                    <span
                      className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold ${formatBadgeColor(report.format)}`}
                    >
                      {report.format?.toUpperCase()}
                    </span>
                  </td>
                  <td className="py-4 px-4 text-right">
                    <button
                      type="button"
                      onClick={() => onDownload?.(report)}
                      className="inline-flex items-center gap-2 px-3 py-2 bg-[#22D3EE]/10 text-[#22D3EE] rounded-lg hover:bg-[#22D3EE]/20 transition-colors"
                    >
                      <Download className="w-4 h-4" />
                      <span className="text-sm font-medium">Download</span>
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
