import { Download, Search } from "lucide-react";
import { useState } from "react";

export function ReportsHistoryTable() {
  const [searchQuery, setSearchQuery] = useState("");

  const reportsHistory = [
    {
      id: 1,
      name: "Threat Summary - February 2026",
      type: "Threat Summary Report",
      dateGenerated: "Mar 5, 2026 14:23",
      generatedBy: "Admin User",
      format: "PDF",
      size: "2.4 MB",
    },
    {
      id: 2,
      name: "Weekly Network Security Analysis",
      type: "Network Security Report",
      dateGenerated: "Mar 4, 2026 09:15",
      generatedBy: "Security Team",
      format: "CSV",
      size: "1.8 MB",
    },
    {
      id: 3,
      name: "AI Detection Performance Q1",
      type: "AI Detection Performance Report",
      dateGenerated: "Mar 1, 2026 16:45",
      generatedBy: "Admin User",
      format: "JSON",
      size: "856 KB",
    },
    {
      id: 4,
      name: "Log Activity Analysis - Week 9",
      type: "Log Activity Report",
      dateGenerated: "Feb 28, 2026 11:30",
      generatedBy: "SOC Analyst",
      format: "PDF",
      size: "3.1 MB",
    },
    {
      id: 5,
      name: "Monthly Threat Summary - January",
      type: "Threat Summary Report",
      dateGenerated: "Feb 1, 2026 08:00",
      generatedBy: "Admin User",
      format: "PDF",
      size: "2.7 MB",
    },
    {
      id: 6,
      name: "Network Intrusion Attempts",
      type: "Network Security Report",
      dateGenerated: "Jan 25, 2026 13:20",
      generatedBy: "Security Team",
      format: "CSV",
      size: "1.2 MB",
    },
  ];

  const filteredReports = reportsHistory.filter(
    (report) =>
      report.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      report.type.toLowerCase().includes(searchQuery.toLowerCase()),
  );

  const formatBadgeColor = (format) => {
    switch (format.toLowerCase()) {
      case "pdf":
        return "bg-[#EF4444]/20 text-[#EF4444]";
      case "csv":
        return "bg-[#10B981]/20 text-[#10B981]";
      case "json":
        return "bg-[#22D3EE]/20 text-[#22D3EE]";
      default:
        return "bg-[#F59E0B]/20 text-[#F59E0B]";
    }
  };

  return (
    <div className="bg-[#1E293B] border border-[#334155] rounded-lg p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-lg font-semibold text-white">
            Generated Reports History
          </h3>
          <p className="text-sm text-gray-400 mt-1">
            Download and manage previously generated reports
          </p>
        </div>
      </div>

      {/* Search Bar */}
      <div className="mb-6">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search reports..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#0F172A] border border-[#334155] rounded-lg pl-10 pr-4 py-2.5 text-white placeholder-gray-500 focus:outline-none focus:border-[#22D3EE] transition-colors"
          />
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-[#334155]">
              <th className="text-left text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4">
                Report Name
              </th>
              <th className="text-left text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4">
                Report Type
              </th>
              <th className="text-left text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4">
                Date Generated
              </th>
              <th className="text-left text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4">
                Generated By
              </th>
              <th className="text-left text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4">
                Format
              </th>
              <th className="text-right text-xs font-semibold text-gray-400 uppercase tracking-wider py-3 px-4">
                Action
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#334155]">
            {filteredReports.map((report) => (
              <tr
                key={report.id}
                className="hover:bg-[#0F172A] transition-colors"
              >
                <td className="py-4 px-4">
                  <p className="text-sm font-medium text-white">
                    {report.name}
                  </p>
                  <p className="text-xs text-gray-400 mt-1">{report.size}</p>
                </td>
                <td className="py-4 px-4">
                  <span className="text-sm text-gray-300">{report.type}</span>
                </td>
                <td className="py-4 px-4">
                  <span className="text-sm text-gray-300">
                    {report.dateGenerated}
                  </span>
                </td>
                <td className="py-4 px-4">
                  <span className="text-sm text-gray-300">
                    {report.generatedBy}
                  </span>
                </td>
                <td className="py-4 px-4">
                  <span
                    className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold ${formatBadgeColor(report.format)}`}
                  >
                    {report.format}
                  </span>
                </td>
                <td className="py-4 px-4 text-right">
                  <button
                    className="inline-flex items-center gap-2 px-3 py-2 bg-[#22D3EE] bg-opacity-10 text-[#22D3EE] rounded-lg hover:bg-opacity-20 transition-colors"
                    aria-label={`Download report ${report.name}`}
                  >
                    <Download className="w-4 h-4 text-white" />
                    <span className="text-sm font-medium text-white">
                      Download
                    </span>
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {filteredReports.length === 0 && (
          <div className="text-center py-12">
            <p className="text-gray-400">
              No reports found matching your search.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
