# Generated by Django 4.2.7 on 2026-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='detected_by',
            field=models.CharField(default='Rule/ML/AI', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=10),
        ),
    ]
