# Generated by Django 4.2.7 on 2026-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_detected_by_alter_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
