# Generated by Django 4.2.7 on 2026-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_attack_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='severity_score',
            field=models.IntegerField(default=0),
        ),
    ]
