# Generated by Django 4.2.7 on 2026-03-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_remove_alert_alert_type_alert_severity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity_score',
            field=models.IntegerField(default=1),
        ),
    ]
