# Generated by Django 4.2.7 on 2026-03-29 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('threat_summary', 'Threat Summary Report'), ('log_activity', 'Log Activity Report'), ('network_security', 'Network Security Report'), ('ai_performance', 'AI Detection Performance Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('total_logs', models.IntegerField(default=0)),
                ('total_threats', models.IntegerField(default=0)),
                ('critical_threats', models.IntegerField(default=0)),
                ('top_attack_type', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
