# Generated by Django 4.2.7 on 2026-03-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networklog',
            old_name='processed',
            new_name='is_suspicious',
        ),
        migrations.RemoveField(
            model_name='networklog',
            name='packet_size',
        ),
        migrations.RemoveField(
            model_name='networklog',
            name='raw_log',
        ),
        migrations.AddField(
            model_name='networklog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networklog',
            name='ml_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='networklog',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='dst_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='src_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
