# Generated by Django 4.2.7 on 2026-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_processed_networklog_is_suspicious_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
