# Generated by Django 4.2.7 on 2026-03-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_networklog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networklog',
            old_name='description',
            new_name='log_type',
        ),
    ]
