# Generated by Django 4.2.7 on 2026-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_description_networklog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklog',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='networklog',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networklog',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networklog',
            name='process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networklog',
            name='raw_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
