# Generated by Django 4.2.7 on 2026-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_networklog_event_type_networklog_host_networklog_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklog',
            name='sequence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networklog',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
