# Generated by Django 4.2.7 on 2026-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_networklog_sequence_index_networklog_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='log_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_logs', models.IntegerField(default=0)),
                ('valid_logs', models.IntegerField(default=0)),
                ('invalid_logs', models.IntegerField(default=0)),
                ('parse_errors', models.IntegerField(default=0)),
                ('threats_found', models.IntegerField(default=0)),
                ('clean_logs', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
