# Generated by Django 4.2.7 on 2026-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklog',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
