# Generated by Django 4.2.7 on 2026-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_networklog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
