# Generated by Django 4.2.7 on 2026-04-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_networklog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
