# Generated by Django 4.2.7 on 2026-05-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_rename_upload_at_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklog',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
    ]
